### ISSUE TITLE
Can't figure out how to have Babel applied to some of the node_modules?

### ISSUE THREAD

**Issue by thenickdude** [AnomalyInnovations/serverless-nodejs-starter#18]
I'm pulling my hair out trying to get Babel to transform some of my node_modules, which use async functions and so need to be transformed as they are packed.

I modified a copy of `serverless-nodejs-starter` to show what I'm trying to do. It just moves the "hello world" response generation out into a separate package which is included:

https://github.com/thenickdude/serverless-nodejs-starter

This is the package which is included:

https://github.com/thenickdude/serverless-nodejs-starter-dep

I modified my webpack configuration like so to remove the "excludes" bit and add a new "include" for the dependency that needs transformed:

```js
  module: {
    rules: [{
      test: /\.js$/,
      loader: 'babel-loader',
      include: [__dirname, path.join(__dirname, 'node_modules', 'serverless-node-starter-dep')]
    }]
  }
```

Running `sls package` and examining the result, it's clear that the `serverless-node-starter-dep` package isn't being transformed by Babel. Trying to invoke it locally fails, complaining about the async keyword in that untransformed dependency.

I'm a Webpack newbie, so I think I'm missing something easy here.

**Comment by thenickdude** [comment]
Figured it out! I needed to add the package to the nodeExternals whitelist and avoid excluding it:

```js
externals: [nodeExternals({whitelist: ["serverless-nodejs-starter-dep"]})],
  // Run babel on all .js files and skip those in node_modules
  module: {
    rules: [{
      test: /\.js$/,
      loader: 'babel-loader',
      include: __dirname,
      exclude: /node_modules\/(?!serverless-nodejs-starter-dep)/
    }]
  }

**Comment by jayair** [comment]
@thenickdude Yeah the whole include/exclude bit is weirdly confusing.
