### ISSUE TITLE
Webpack 4 support

### ISSUE THREAD

**Issue by MatissJanis** [AnomalyInnovations/serverless-nodejs-starter#23]
As soon as I upgrade webpack to version 4, the whole project breaks.

**Comment by jayair** [comment]
@MatissJanis Yeah we are looking into it. So far we holding it to Webpack 3.11.0 while we fix it.

**Comment by tbaustin** [comment]
Any update ? What breaks with the project for you @MatissJanis ?

**Comment by jayair** [comment]
@tbaustin We updated to Webpack 4 recently - https://github.com/AnomalyInnovations/serverless-nodejs-starter/releases/tag/v1.3.

**Comment by jo** [comment]
@jayair this issue can then be closed, right? :)

**Comment by jayair** [comment]
Yup! Thanks.
