### ISSUE TITLE
serverless offline not works (at nodejs8.10)

### ISSUE THREAD

**Issue by ruucm-working** [AnomalyInnovations/serverless-nodejs-starter#32]
When I type `serverless offline start` like README, it does not works with below error

URL: http://localhost:3000/hello

```
{
  "statusCode": 404,
  "error": "Serverless-offline: route not found.",
  "currentRoute": "get - /hello",
  "existingRoutes": [
    
  ]
}
```

+additional log at my terminal

`Serverless: Warning: found unsupported runtime 'nodejs8.10'`

**Comment by jayair** [comment]
@ruucm-working You are right. I'll update to the latest `serverless offline` in a sec.

**Comment by jayair** [comment]
@ruucm-working Updated. For your project, run `npm install --save-dev serverless-offline` to update it.

**Comment by ruucm-working** [comment]
@jayair awesome
