### ISSUE TITLE
Errors with webpack.config.js generation

### ISSUE THREAD

**Issue by mikedizon** [AnomalyInnovations/serverless-nodejs-starter#33]
const slsw = require("serverless-webpack");
const nodeExternals = require("webpack-node-externals");

module.exports = {
  entry: slsw.lib.entries,
  target: "node",
  // Generate sourcemaps for proper error messages
  devtool: 'source-map',
  // Since 'aws-sdk' is not compatible with webpack,
  // we exclude all node dependencies
  **exlear
  ternals: [nodeExternals()],**
  mode: slsw.lib.webpack.isLocal ? "development" : "production",
  optimization: {
    // We no not want to minimize our code.
    minimize: false
  },
  performance: {
    // Turn off size warnings for entry points
    hints: false
  },
  // Run babel on all .js files and skip those in node_modules
  module: {
    rules: [
      {
        test: /\.js$/,
        loader: "babel-loader",
        include: __dirname,
        exclude: /node_modules/
      }
    ]
  }
};

**Comment by jayair** [comment]
@mikedizon What is the issue you are seeing?

**Comment by mikedizon** [comment]
@jayair I highlighted it in bold. The generated webpack.config.js file misspells 'externals'

**Comment by jayair** [comment]
@mikedizon I guess I'm not really following. How are you generating the `webpack.config.js`?

**Comment by mikedizon** [comment]
Disregard. I must have had the file open and on that line and hit enter or something. Apologies.

**Comment by jayair** [comment]
@mikedizon No worries!
